apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: Hello
spec:
  selector:
    matchLabels:
      app: Hello
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: Hello
    spec:
      containers:
        - name: spring-boot-k8s
          image: hello1-img # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster